const $ = (selector) => document.querySelector(selector);
const storageKey = "hipfAdminSettings";
const settings = { ...JSON.parse(localStorage.getItem(storageKey) || "{}"), ...window.HIPF_CONFIG };
let token = sessionStorage.getItem("hipfAdminToken") || "";
let registrations = [];
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[character]);

function showMessage(selector, message, state = "") { const element = $(selector); element.textContent = message; element.className = `form-result ${state}`; }
function saveSettings() { settings.apiUrl = $("#api-url").value.trim().replace(/\/$/, ""); settings.userPoolId = $("#user-pool-id").value.trim(); settings.clientId = $("#client-id").value.trim(); localStorage.setItem(storageKey, JSON.stringify(settings)); }
function configured() { return settings.apiUrl && settings.userPoolId && settings.clientId; }
function cognitoRegion() { return settings.userPoolId.split("_")[0]; }
function request(path, options = {}) { return fetch(`${settings.apiUrl}${path}`, { headers: { Authorization: token, "Content-Type":"application/json", ...options.headers }, ...options }).then(async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `Request failed (${response.status}).`); return body; }); }
function tokenEmail() { try { return JSON.parse(atob(token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"))).email || "Foundation admin"; } catch { return "Foundation admin"; } }
function showDashboard() { $("#login-panel").hidden = true; $("#dashboard").hidden = false; $("#sign-out").hidden = false; $("#admin-email").textContent = tokenEmail(); loadRegistrations(); }
function renderRows() { const filter = $("#search").value.trim().toLowerCase(); const shown = registrations.filter((item) => [item.name,item.email,item.eventName,item.eventId].join(" ").toLowerCase().includes(filter)); const body = $("#registrations-table"); body.innerHTML = shown.length ? shown.map((item) => `<tr><td><strong>${escapeHtml(item.name || "Unnamed attendee")}</strong><span>${escapeHtml(item.email)}</span></td><td><strong>${escapeHtml(item.eventName || item.eventId)}</strong><span>${escapeHtml(item.eventId)}</span></td><td>${escapeHtml(new Date(item.createdAt).toLocaleString())}</td><td><span class="status-pill">${escapeHtml(item.status || "confirmed")}</span></td><td><button class="admin-cancel" data-id="${escapeHtml(item.registrationId)}">Cancel</button></td></tr>`).join("") : "<tr><td class='empty' colspan='5'>No matching registrations.</td></tr>"; body.querySelectorAll("button").forEach((button) => button.addEventListener("click", () => cancelRegistration(button.dataset.id))); }
async function loadRegistrations() { try { showMessage("#table-status", "Loading registrations…"); const data = await request("/admin/registrations"); registrations = data.registrations || []; $("#registration-count").textContent = registrations.length; $("#attendee-count").textContent = new Set(registrations.map((item) => item.email)).size; $("#event-count").textContent = new Set(registrations.map((item) => item.eventId)).size; renderRows(); showMessage("#table-status", `${registrations.length} registration${registrations.length === 1 ? "" : "s"} loaded.`, "success"); } catch (error) { showMessage("#table-status", error.message, "error"); if (/403|401|Admin access/.test(error.message)) { sessionStorage.removeItem("hipfAdminToken"); token = ""; } } }
async function cancelRegistration(id) { if (!confirm("Cancel this attendee registration?")) return; try { await request(`/admin/registration/${encodeURIComponent(id)}`, { method:"DELETE" }); await loadRegistrations(); } catch (error) { showMessage("#table-status", error.message, "error"); } }
function exportCsv() { const rows = [["Name","Email","Event","Registration ID","Status","Created at"], ...registrations.map((item) => [item.name || "",item.email || "",item.eventName || item.eventId,item.registrationId,item.status || "",item.createdAt || ""])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(new Blob([csv], { type:"text/csv" })), download:"home-in-prison-registrations.csv" }); link.click(); URL.revokeObjectURL(link.href); }

$("#api-url").value = settings.apiUrl || ""; $("#user-pool-id").value = settings.userPoolId || ""; $("#client-id").value = settings.clientId || "";
$("#save-settings").addEventListener("click", () => { saveSettings(); showMessage("#settings-result", configured() ? "Settings saved." : "Complete all three settings.", configured() ? "success" : "error"); });
$("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); saveSettings(); if (!configured()) return showMessage("#login-result", "Save the API URL, User Pool ID, and App Client ID first.", "error"); try { showMessage("#login-result", "Signing in…"); const response = await fetch(`https://cognito-idp.${cognitoRegion()}.amazonaws.com/`, { method:"POST", headers:{ "Content-Type":"application/x-amz-json-1.1", "X-Amz-Target":"AWSCognitoIdentityProviderService.InitiateAuth" }, body:JSON.stringify({ AuthFlow:"USER_PASSWORD_AUTH", ClientId:settings.clientId, AuthParameters:{ USERNAME:$("#login-email").value.trim(), PASSWORD:$("#login-password").value } }) }); const data = await response.json(); if (!response.ok || !data.AuthenticationResult) throw new Error(data.message || "Sign-in failed. Ensure this user is in the Admins group."); token = data.AuthenticationResult.IdToken; sessionStorage.setItem("hipfAdminToken", token); showDashboard(); } catch (error) { showMessage("#login-result", error.message, "error"); } });
$("#refresh").addEventListener("click", loadRegistrations); $("#search").addEventListener("input", renderRows); $("#export-csv").addEventListener("click", exportCsv); $("#sign-out").addEventListener("click", () => { sessionStorage.removeItem("hipfAdminToken"); location.reload(); }); if (token && configured()) showDashboard();
